import { z } from 'zod';
import { CategoryAssignmentBasis } from '../enums/category-assignment-basis';
import { CategoryAssignmentIssueCode } from '../enums/category-assignment-issue-code';
import { CategoryAssignmentStatus } from '../enums/category-assignment-status';
import { CategoryOverrideStatus } from '../enums/category-override-status';
import { CaseworkStatus } from '../enums/casework-status';
import { ContractType } from '../enums/contract-type';
import { CountryCode } from '../enums/country-code';
import { EmploymentType } from '../enums/employment-type';
import { EuCoreMetricId } from '../enums/eu-core-metric-id';
import { EuCoreMetricResultStatus } from '../enums/eu-core-metric-result-status';
import { Gender } from '../enums/gender';
import { IntakeColumnType } from '../enums/intake-column-type';
import { IntakeFileStatus } from '../enums/intake-file-status';
import { IntakeSnapshotBlockedReason } from '../enums/intake-snapshot-blocked-reason';
import { JobNormalizationIssueCode } from '../enums/job-normalization-issue-code';
import { LogicalIntakeField } from '../enums/logical-intake-field';
import { MappingNormalizationIssueCode } from '../enums/mapping-normalization-issue-code';
import { PayComponent } from '../enums/pay-component';
import { RemediationStatus } from '../enums/remediation-status';
import { ReviewStatus } from '../enums/review-status';
import { SnapshotStatus } from '../enums/snapshot-status';
import { StructuralIssueCode } from '../enums/structural-issue-code';
import { WorkerStatus } from '../enums/worker-status';

export const CategoryAssignmentStatusSchema = z.nativeEnum(CategoryAssignmentStatus);
export const CategoryAssignmentBasisSchema = z.nativeEnum(CategoryAssignmentBasis);
export const CategoryAssignmentIssueCodeSchema = z.nativeEnum(CategoryAssignmentIssueCode);
export const CategoryOverrideStatusSchema = z.nativeEnum(CategoryOverrideStatus);
export const WorkerStatusSchema = z.nativeEnum(WorkerStatus);
export const EmploymentTypeSchema = z.nativeEnum(EmploymentType);
export const ContractTypeSchema = z.nativeEnum(ContractType);
export const EuCoreMetricIdSchema = z.nativeEnum(EuCoreMetricId);
export const EuCoreMetricResultStatusSchema = z.nativeEnum(EuCoreMetricResultStatus);
export const GenderSchema = z.nativeEnum(Gender);
export const PayComponentSchema = z.nativeEnum(PayComponent);
export const SnapshotStatusSchema = z.nativeEnum(SnapshotStatus);
export const CaseworkStatusSchema = z.nativeEnum(CaseworkStatus);
export const RemediationStatusSchema = z.nativeEnum(RemediationStatus);
export const ReviewStatusSchema = z.nativeEnum(ReviewStatus);
export const CountryCodeSchema = z.nativeEnum(CountryCode);
export const IntakeFileStatusSchema = z.nativeEnum(IntakeFileStatus);
export const IntakeColumnTypeSchema = z.nativeEnum(IntakeColumnType);
export const StructuralIssueCodeSchema = z.nativeEnum(StructuralIssueCode);
export const LogicalIntakeFieldSchema = z.nativeEnum(LogicalIntakeField);
export const JobNormalizationIssueCodeSchema = z.nativeEnum(JobNormalizationIssueCode);
export const MappingNormalizationIssueCodeSchema = z.nativeEnum(MappingNormalizationIssueCode);
export const IntakeSnapshotBlockedReasonSchema = z.nativeEnum(IntakeSnapshotBlockedReason);
