export enum IntakeSnapshotBlockedReason {
  MAPPING_GATED = 'MAPPING_GATED',
  MAPPING_NOT_OK = 'MAPPING_NOT_OK',
  FILE_ISSUES_PRESENT = 'FILE_ISSUES_PRESENT',
  NO_NORMALIZED_ROWS = 'NO_NORMALIZED_ROWS',
  INCOMPLETE_ROW_MAPPING = 'INCOMPLETE_ROW_MAPPING',
}
