/**
 * Stable codes for job normalization (S08). Used for reviewable, deterministic issue capture.
 * Not comparable-worker categories or equal-value outcomes.
 */
export enum JobNormalizationIssueCode {
  JOB_NORM_MISSING_JOB_TITLE = 'JOB_NORM_MISSING_JOB_TITLE',
  JOB_NORM_INVALID_FAMILY_CODE = 'JOB_NORM_INVALID_FAMILY_CODE',
  JOB_NORM_INVALID_SUBFAMILY_CODE = 'JOB_NORM_INVALID_SUBFAMILY_CODE',
  JOB_NORM_AMBIGUOUS_GRADE_OR_LEVEL = 'JOB_NORM_AMBIGUOUS_GRADE_OR_LEVEL',
  JOB_NORM_UNMAPPED_GRADE_OR_LEVEL = 'JOB_NORM_UNMAPPED_GRADE_OR_LEVEL',
  JOB_NORM_JOB_FIELD_WRONG_SCALAR_KIND = 'JOB_NORM_JOB_FIELD_WRONG_SCALAR_KIND',
}
