export enum MappingNormalizationIssueCode {
  GATING_FILE_NOT_STRUCTURALLY_VALID = 'GATING_FILE_NOT_STRUCTURALLY_VALID',
  PROFILE_MISSING_REQUIRED_FIELD_MAPPING = 'PROFILE_MISSING_REQUIRED_FIELD_MAPPING',
  PROFILE_SOURCE_COLUMN_NOT_IN_FILE = 'PROFILE_SOURCE_COLUMN_NOT_IN_FILE',
  ROW_EMPTY_REQUIRED_VALUE = 'ROW_EMPTY_REQUIRED_VALUE',
  ROW_INVALID_GENDER_VALUE = 'ROW_INVALID_GENDER_VALUE',
  ROW_INVALID_DECIMAL_VALUE = 'ROW_INVALID_DECIMAL_VALUE',
  ROW_INVALID_STRING_VALUE = 'ROW_INVALID_STRING_VALUE',
  PARSE_ERROR_UNEXPECTED_EMPTY_TABLE = 'PARSE_ERROR_UNEXPECTED_EMPTY_TABLE',
}
