export enum PayComponentType {
  BASE_SALARY = 'BASE_SALARY',
  VARIABLE_PAY = 'VARIABLE_PAY',
  BONUS = 'BONUS',
  COMMISSION = 'COMMISSION',
  OVERTIME = 'OVERTIME',
  ALLOWANCE = 'ALLOWANCE',
  BENEFIT_IN_KIND = 'BENEFIT_IN_KIND',
  EMPLOYER_PENSION_CONTRIBUTION = 'EMPLOYER_PENSION_CONTRIBUTION',
  OTHER = 'OTHER',
}
