export enum StructuralIssueCode {
  EMPTY_FILE = 'EMPTY_FILE',
  PARSE_ERROR = 'PARSE_ERROR',
  MISSING_HEADER_ROW = 'MISSING_HEADER_ROW',
  DUPLICATE_HEADER = 'DUPLICATE_HEADER',
  MISSING_REQUIRED_COLUMN = 'MISSING_REQUIRED_COLUMN',
  EMPTY_REQUIRED_FIELD = 'EMPTY_REQUIRED_FIELD',
  TYPE_MISMATCH = 'TYPE_MISMATCH',
}
